err.name: explanation
DataError: parameters to idb request where invalid
